namespace PirateQuester.DFK.Contracts;

public enum QuestType
{
	TRAINING_STRENGTH = 1,
	TRAINING_DEXTERITY = 2,
	TRAINING_AGILITY = 3,
	TRAINING_VITALITY = 4,
	TRAINING_ENDURANCE = 5,
	TRAINING_WISDOM = 6,
	TRAINING_INTELLIGENCE = 7,
	TRAINING_LUCK = 8,
	GOLD_MINING = 9,
	CRYSTAL_MINING = 10,
	FISHING = 11,
	FORAGING = 12,
	GARDENING_CRYSTAL_AVAX = 13,
	GARDENING_CRYSTAL_wJEWEL = 14,
	GARDENING_CRYSTAL_USD = 15,
	GARDENING_ETH_USDC = 16,
	GARDENING_wJEWEL_USDC = 17,
	GARDENING_CRYSTAL_ETH = 18,
	GARDENING_CRYSTAL_BTC = 19,
	GARDENING_CRYSTAL_KLA = 20,
	GARDENING_JEWEL_KLAY = 21,
	GARDENING_JEWEL_AVAX = 22,
	GARDENING_JEWEL_BTCb = 23,
	GARDENING_JEWEL_ETH = 24,
	GARDENING_BTCb_USDC = 25
}
